services:
  exporter:
    image: exporter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9399:9399"
    volumes:
      - ${PWD}/collectors:/app/collectors
      - ${PWD}/sql_exporter.yml:/app/sql_exporter.yml
    environment:
      - SQL_EXPORTER_VERSION=0.15.0

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

volumes:
  prometheus_data:

networks:
  default:
    driver: bridge
