collector_name: curio_config
min_interval: 1m

metrics:
  - metric_name: curio_config_total_count
    type: gauge
    help: 'Total number of configurations'
    values: [total_count]
    query: |
      SELECT COUNT(*) AS total_count FROM harmony_config
